"""Add gender field to diagnose_histories table

Revision ID: c9f6a58fa29d
Revises: da3285c716e0
Create Date: 2025-09-04 10:14:43.855721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f6a58fa29d'
down_revision = 'da3285c716e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnose_histories', sa.Column('gender', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnose_histories', 'gender')
    # ### end Alembic commands ###
